/* CARD ACTION TYPES */
export const CREATE_CARD = 'CREATE_CARD';
export const DELETE_CARD = 'DELETE_CARD';

/* COLUMN ACTION TYPES */
export const ATTACH_CARD = 'ATTACH_CARD';
export const DETACH_CARD = 'DETACH_CARD';
