/* BOARD ACTION TYPES */
export const UPDATE_BOARD_TITLE = 'UPDATE_BOARD_TITLE';

/* COLUMN ACTION TYPES */
export const ATTACH_CARD = 'ATTACH_CARD';
export const DETACH_CARD = 'DETACH_CARD';
export const DROP_CARD_ON_FRAME = 'DROP_CARD_ON_FRAME';


/* CARD ACTION TYPES */
export const CREATE_CARD = 'CREATE_CARD';
export const DELETE_CARD = 'DELETE_CARD';
export const UPDATE_CARD_DESCRIPTION = 'UPDATE_CARD_DESCRIPTION';


/* CHECKLIST ACTION TYPES */
export const ADD_CHECKLIST = 'ADD_CHECKLIST';
export const DELETE_CHECKLIST = 'DELETE_CHECKLIST';
export const UPDATE_CHECKLIST_TITLE = 'UPDATE_CHECKLIST_TITLE';
export const TOGGLE_CHECKLIST_ITEM = 'TOGGLE_CHECKLIST_ITEM';
export const ADD_CHECKLIST_ITEM = 'ADD_CHECKLIST_ITEM';
export const UPDATE_CHECKLIST_ITEM_TEXT = 'UPDATE_CHECKLIST_ITEM_TEXT';
export const DELETE_CHECKLIST_ITEM = 'DELETE_CHECKLIST_ITEM';


/* AUTH ACTION TYPES */
export const AUTH_USER = 'AUTH_USER';